### ISSUE TITLE
Automatically updating the readme is removing node modules (react) in spectacle-docs

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/builder-docs-archetype#3]
Repro:

```
$ git clone git@github.com:FormidableLabs/spectacle-docs.git
$ cd spectacle-docs
$ git checkout task-addArchetype
$ npm install
# Add `"update-readme": "npm update"` to the `"scripts"` section of `spectacle-docs/package.json`
$ builder run update-readme
```

Context: We want to automatically update each project to its latest `master` so the landing page reflects the most up-to-date `README.md`.

In the archetype, we are using `"build-static": "npm update && builder run webpack-static && ..."` to pull in the latest updates. 

In `spectacle-docs`, it has `"react": "^0.14.5",`. The latest is `0.14.7`, so running `npm update` directly in the project updates it to `0.14.7`. 

Problem: For testing, I created `"update-readme": "npm update"`. Running `builder run update-readme` removes `react` from `node_modules`; it looks like it points to `node_modules/spectacle/react` (not sure if this is the case). When we run `webpack-static`, webpack cannot resolve the `react` module. 

Run `builder run update-readme` in `spectacle-docs`:
<img width="1949" alt="screen shot 2016-03-25 at 12 52 29 pm" src="https://cloud.githubusercontent.com/assets/768965/14052579/8b2ebdee-f288-11e5-98e1-9766671a293c.png">

`node_modules/react` is missing:
<img width="727" alt="screen shot 2016-03-25 at 12 52 37 pm" src="https://cloud.githubusercontent.com/assets/768965/14052600/a901bdc6-f288-11e5-8d15-ee9770cfb616.png">

The resulting error is that webpack cannot resolve module `react`: 
<img width="1319" alt="screen shot 2016-03-25 at 1 06 27 pm" src="https://cloud.githubusercontent.com/assets/768965/14052849/699d8a64-f28a-11e5-932d-c58843abf3c4.png">

_aside_ Running `npm update` directly works just fine:
<img width="1949" alt="screen shot 2016-03-25 at 12 56 55 pm" src="https://cloud.githubusercontent.com/assets/768965/14052666/17946bee-f289-11e5-856e-6d03851efa14.png">

@coopy Should I remove `npm update` from the archetype and put it in each project instead?

**Comment by paulathevalley** [comment]
Alternatively, is there a way to granularly update just the project we want? e.g.
In `spectacle-docs`, the archetype runs `npm update spectacle`;
In `builder-docs`, the archetype runs `npm update builder`; 
etc. 

For `victory-docs`, we might want to update the `README.md`s of all the victory components. _shrug_

**Comment by paulathevalley** [comment]
@david-davidson’s idea: 

In archetype:

``` json
"update-project": "echo U NEED '2' DEFINE THIS IN UR PROJECT"
```

In project: 

``` json
"update-project": "npm update spectacle" 
```

**Comment by coopy** [comment]
@ryan-roemer could you assist with this?

**Comment by paulathevalley** [comment]
Upgrading `npm install -g npm@latest

**Comment by paulathevalley** [comment]
Ok, upgrading npm and uninstalling builder globally resolved this! 
Steps: `npm install -g npm@latest`, `npm uninstall -g builder`, and following https://github.com/FormidableLabs/builder#path-augmentation 
Hooray.
